//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressionLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINKIND
    {
        public string KINDNO { get; set; }
        public string SID { get; set; }
        public string KINDNAME { get; set; }
        public Nullable<decimal> PAY2 { get; set; }
        public Nullable<decimal> PAY3 { get; set; }
        public Nullable<decimal> PAY4 { get; set; }
        public Nullable<decimal> PAYT { get; set; }
        public Nullable<decimal> PAYA { get; set; }
        public Nullable<decimal> PAYS { get; set; }
        public Nullable<decimal> BONUS2 { get; set; }
        public Nullable<decimal> BONUS3 { get; set; }
        public Nullable<decimal> BONUS4 { get; set; }
        public Nullable<decimal> BONUST { get; set; }
        public Nullable<decimal> BONUSA { get; set; }
        public Nullable<int> NUMCOUNT { get; set; }
        public Nullable<int> BINCOUNT { get; set; }
        public Nullable<decimal> PAYSM2 { get; set; }
        public Nullable<decimal> PAYSM3 { get; set; }
        public Nullable<decimal> PAYSM { get; set; }
        public Nullable<decimal> BONUSSM2 { get; set; }
        public Nullable<decimal> BONUSSM { get; set; }
        public Nullable<decimal> BONUSSM3 { get; set; }
    }
}
